apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: money-tracker
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  replicas: 3
  selector:
    matchLabels:
      app: money-tracker
  template:
    metadata:
      labels:
        app: money-tracker
    spec:
      containers:
        - name: money-tracker
          imagePullPolicy: Always
          image: IMAGE
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 10
