---
- name: "Setup Jenkins build environment play."
  hosts: ec2-jenkins
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  roles:
    - install-jenkins
    - install-docker
    - install-hadolint
    - install-awscli
    - install-eksctl
    - install-kubectl
    - reboot
